version: '3.8'

services:
  # The Database
  db:
    image: postgres:15-alpine
    container_name: vryndara-db
    restart: always
    environment:
      POSTGRES_USER: vryndara
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: vryndara_core
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # A simple Web UI to view the database (so you don't need CLI)
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data: